### ISSUE TITLE
20210306 Crash on W10

### ISSUE THREAD

**Issue by 5axes** [smartavionics/Cura#101]
Last release Crash on Windows 10 just when I launch the slice operation. 

Occurs on every geometry not dedicate to a special part.   Printer Ender 3

![image](https://user-images.githubusercontent.com/11015345/110216425-6d1e2200-7eaf-11eb-8f6a-c6624698384d.png)

In the Log file I have an error in relation to the "PrintInformation.py" 

And something regarding an user "**burto** ????" . It's not a account existing on my Pc.

IE : 
`File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.5\site-packages\cura\UI\PrintInformation.py"`

Log file
[cura.log](https://github.com/smartavionics/Cura/files/6095843/cura.log)

**Comment by smartavionics** [comment]
Hi, I think it is the custom job prefix plugin that has a problem, can you try disabling that and see if the slice succeeds. If it does, then you need to raise an issue either on the upstream UM Cura repo, or on the provider of that plugin.

**Comment by 5axes** [comment]
I'm sorry I have switched back to the previous release .. But I don't think that this issue can came from a plugin because before to send my report , I have perform a fresh install in a new folder and the user  Roaming configuration folder have been completely deleted so normaly no 3d party plugin was activated with this release.

**Comment by smartavionics** [comment]
Well, in the log file it refers to:
```
File "C:\Users\5axes\AppData\Roaming\cura\master\plugins\CustomJobPrefix\CustomJobPrefix\PrintInformationPatches.py"
```

That's where the error is occurring.

**Comment by 5axes** [comment]
Yes I have seen this line ???  I should not have any plugin ... Ok I will try to re_install the last release.

**Comment by smartavionics** [comment]
As far as I can tell, in the upstream UM code they recently removed the function that your log file says is undefined. I note that the custom job prefix plugin has recently been updated and it appears to include that function so maybe you just need to update that plugin?

**Comment by 5axes** [comment]
Ok no more crash :( but I have now something very strange on my first test part

Visualisation Layer 301 

![image](https://user-images.githubusercontent.com/11015345/110218012-aa86ad80-7eb7-11eb-81a9-9d6fd47d3b89.png)

Visualisation layer 302

![image](https://user-images.githubusercontent.com/11015345/110218026-ba9e8d00-7eb7-11eb-8e78-4a592a738c6d.png)

[Slant_Roof_Paddle_Boat_Master.zip](https://github.com/smartavionics/Cura/files/6095918/Slant_Roof_Paddle_Boat_Master.zip)

**Comment by 5axes** [comment]
Ok I think it's time to stop ... for today.

Close and Save the project. Load again and everything is OK 

![image](https://user-images.githubusercontent.com/11015345/110218224-bc1c8500-7eb8-11eb-9003-b5b8eafd0820.png)

**Comment by 5axes** [comment]
I'm Sorry to bother you with this false report !!

**Comment by smartavionics** [comment]
No problem. When you are living on the leading edge, stuff (code, plugins, cache files, etc.) can get out of sync. It happens to me also from time to time.
