### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by qwerty8224** [smartavionics/Cura#102]
Layer 37 stands out from the rest ...
![Снимок экрана (21)_LI](https://user-images.githubusercontent.com/19486373/111025977-d72b4f80-83f8-11eb-9dda-e28d4b81a086.jpg)

**Comment by smartavionics** [comment]
Can you provide the project file, please?

**Comment by qwerty8224** [comment]
[1DXU_Крепление дуги  к плоту (1).zip](https://github.com/smartavionics/Cura/files/6134477/1DXU_.1.zip)

**Comment by smartavionics** [comment]
That change in the diameter is due to the hole horizontal expansion, setting it to 0, makes the step go away. There's nothing I can do to avoid this.

![Screenshot_2021-03-13_09-57-52](https://user-images.githubusercontent.com/585618/111026564-b821c300-83e2-11eb-9f18-931e55110622.png)

**Comment by qwerty8224** [comment]
sorry for bothering you (((I just wanted to check this but didn't have time. Thanks)

**Comment by smartavionics** [comment]
No problem, cheers!
