### ISSUE TITLE
Win64 has 2 build assets - which one should be used?

### ISSUE THREAD

**Issue by KodeMunkie** [smartavionics/Cura#118]
There are 2 versions of the Windows 64 bit build - which one of the following 2 should be used?

Cura-mb-master-win64-20210629-1.exe
193 MB
Cura-mb-master-win64-20210629.exe
193 MB

**Application version**
https://github.com/smartavionics/Cura/releases/tag/20210629

**Platform**
Windows x64

**Printer**
N/A

**Reproduction steps**
Look at the assets page.

**Comment by smartavionics** [comment]
Hi, the -1 asset was built to try and fix a problem for a user (#116) but it didn't make any difference for them so I will remove it.
