### ISSUE TITLE
'Arange all models' packing distance

### ISSUE THREAD

**Issue by PhilBaz** [smartavionics/Cura#161]
**Is your feature request related to a problem? Please describe.**
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

With ABS it's nice to have some distance between parts. I currently mostly have to place them by hand.

**Describe the solution you'd like**
(A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)

It would be nice to be able to set the packing distance with a setting. 10mm minimum distance apart, 20mm minim, etc. 

**Describe alternatives you've considered**
(A clear and concise description of any alternative solutions or features you've considered. Again, if possible, think about why these alternatives are not working out.)

Guess I could create false skirts around parts before exporting them, but that would make more work.

**Affected users and/or printers**
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)

People who use ABS that benefits from a little travel time for the tool head, and less reflected fan air from close by parts.

**Additional context**
(Add any other context or screenshots about the feature request here.)

**Comment by smartavionics** [comment]
Hi, I've spent a few minutes looking at this and have drawn a blank so far. The code appears to set the spacing to a fixed 1.5mm but when I try and change that hard coded value to something larger, it fails saying that it can't fit all the objects in the build plate when it really should be able to. I will try and understand what's happening there.

**Comment by PhilBaz** [comment]
Thanks for looking into it! I think it would be a useful feature. Its one of those things i'm slightly surprised isn't already in there.

**Comment by smartavionics** [comment]
I now understand what was stopping a larger packing working and will think about how to allow the user to specify a value. At the same time, I am also going to look into being able to stop the packer from rotating parts.

**Comment by smartavionics** [comment]
stopping a larger packing DISTANCE working

**Comment by smartavionics** [comment]
I've made a new release that adds experimental settings to control the distance and also to disable the rotations. Changing those settings doesn't automatically trigger the rearrangement, you still have to do Ctrl-R or use the menu option. The arranging is still as quirky as before!

**Comment by PhilBaz** [comment]
Ohh, awesome! Ill download it and give it a shot. Yes, the arranging is quirky to say the least. I do vis work with UV packing so I know what you are talking about. I stopped myself before requesting concave packing :)

**Comment by PhilBaz** [comment]
Oooo, love it!!!  Best part, disable rotation also works for model multiply... What a great addition. From my intal play around everything seems to be working perfectly. Thank you!
