### ISSUE TITLE
Rounding Error / Offset on perimeter walls

### ISSUE THREAD

**Issue by McNugget6750** [smartavionics/Cura#171]
**Application version**
This fork does not provide a build number...

**Platform**
Windows 10

**Printer**
Malyan M180 custom build 

**Reproduction steps**
1. Open a file that has a volume with a cutout and print the top surface of the volume at an angle
2. Notice that the inner perimeter, when the angled surface of the volume breaks up a full circumference and the head needs to turn around instead of continuing counter clock wise, will be printed one perimeter width inward. This is even visible in the slicer preview already.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/12099353/167302340-7764253d-3118-419a-b813-2f85ab511b3e.png)

**Actual results**
![photo_2022-05-08_08-04-14](https://user-images.githubusercontent.com/12099353/167302445-0a348c12-c26e-4b90-a635-e52b474fe95c.jpg)
![photo_2022-05-08_08-04-22](https://user-images.githubusercontent.com/12099353/167302448-1a0c42a2-87b4-4f00-92ff-9255003086bd.jpg)
![photo_2022-05-08_08-04-24](https://user-images.githubusercontent.com/12099353/167302449-209414ee-224c-42a7-b406-00268821ff35.jpg)
![photo_2022-05-08_08-04-27](https://user-images.githubusercontent.com/12099353/167302452-bf5b909d-5162-4837-ab97-bf12ccd740f8.jpg)

**Expected results**
Smooth surface from the rim of the model all the way to the mounting surface of the front plate.

**Project file**
[20220424 - Speakers.zip](https://github.com/smartavionics/Cura/files/8647211/20220424.-.Speakers.zip)

**Log file**
[cura_log.zip](https://github.com/smartavionics/Cura/files/8647215/cura_log.zip)

**Additional information**
It would be nice if we could figure this one out as I have seen this many times on other prints, too, and I always needed to fix this in CAD by adding some sort of 0.1mm-0.2mm offset to those surface. This is the first time I actively looked for it in the slicer and it's clearly visible that the perimeter moves one width inwards for no apparent reason.

**Comment by smartavionics** [comment]
Hi @McNugget6750 , what's happening here is that you have specified a non-zero value for hole horizontal expansion and so as the big cavity in your model is a hole, it gets expanded. You can stop this happening by putting in a value for Hole Horizontal Expansion Max Length which will stop holes whose perimeter length is >= that value from being expanded. Hope this helps!

![Screenshot_2022-05-08_16-45-57](https://user-images.githubusercontent.com/585618/167304130-31b56f4b-4816-4486-96f7-162676a0e57b.png)

**Comment by McNugget6750** [comment]
Wow, that does make a lot of sense! Thank you for the quick reply and excellent thinking! I'll try that!

**Comment by McNugget6750** [comment]
Yes, that fixed it! Thanks a lot!!
