### ISSUE TITLE
Multiple layers for Initial Expansion

### ISSUE THREAD

**Issue by 5axes** [smartavionics/Cura#181]
There is a feature in SuperSlicer that I love and use every time, It's the Initial expansion on Multi-Layer. This option is not present on Cura ant it would be a very nice feature.

This feature is adding a new parameter : Nb of layer for the initial expansion

The number of layers on witch the initial expansion will be active. The first layer will be shrunk by the Initial **Layer Horizontal Expansion** , then the next layer will be gradualy change up to the layer indicated by this parameter to reach the normal **Horizontal expansion.**

![image](https://user-images.githubusercontent.com/11015345/180392658-6a35fe49-eb12-4331-afbd-e9c50d76721e.png)

**Comment by smartavionics** [comment]
Sounds easy enough, I'll take a look...

**Comment by smartavionics** [comment]
Will be in the next release...
![Screenshot_2022-07-25_13-08-54](https://user-images.githubusercontent.com/585618/180774502-0abd2c12-f676-4a61-8e70-3ecfee1a2b7e.png)

**Comment by smartavionics** [comment]
Now in https://github.com/smartavionics/Cura/releases/tag/4.20.3

**Comment by 5axes** [comment]
Thanks a lot !
