### ISSUE TITLE
Dab/dots along skin edge ? Extra moves

### ISSUE THREAD

**Issue by PhilBaz** [smartavionics/Cura#191]
**Application version**
(The version of the application this issue occurs with.)
latest .7

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
win 10
**Printer**
(Which printer was selected in Cura?)
Voron 2.4
**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)

after laying down the initial layer there are a series of additional moves along the perimeter where the walls meet the skin.

  Ive been playing with filter out tiny gaps setting as well as fill gaps setting but cant get it to stop doing these extra dab/dots along the skin perimeter. That made me think its a bug possible?

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

File attached

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

[dab dots.zip](https://github.com/smartavionics/Cura/files/9846914/dab.dots.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by smartavionics** [comment]
I can't see any problem, you'll have to provide more info, e.g. a screen shot showing the bad travels/lines.

**Comment by PhilBaz** [comment]
@smartavionics 

At the end of the first layer. On the player forward until the skin is complete, then you see the extra moves.

**Comment by PhilBaz** [comment]
doesn't really look like much from the travels.
![Screenshot 2022-10-23 100847](https://user-images.githubusercontent.com/21558241/197403058-d7e876e8-2365-4725-9984-6482eaaf944d.jpg)

**Comment by PhilBaz** [comment]
Sorry, one more thing, in case I didn't state it clearly .... they are not linear moves. The nozzle dips down and makes dots a few times along the path.

**Comment by smartavionics** [comment]
Ah yes, I can see now what it's doing. I think it is caused by the Monotonic Top/Bottom Order setting being enabled. Unfortunately, the UM monotonic ordering is still pretty buggy. My monotonic ordering is less buggy but, unfortunately, only works with lines skin pattern and not zigzag.

**Comment by PhilBaz** [comment]
@smartavionics 

Ahhh, okay, good to know. Ill go to lines, no problems there. Thanks for the help!

**Comment by smartavionics** [comment]
UM have been making changes to their monotonic code in Cura 5.x  but I don't think it's easy to retrofit those changes to my 4.20 code.
