### ISSUE TITLE
Slicing error for cube when using both "alternate extra wall" and "visible top skins have only one wall"

### ISSUE THREAD

**Issue by reffu42** [smartavionics/Cura#196]
**Application version**
4.20.8

**Platform**
Windows 10 64-Bit 22H2 (19045). GPU: Radeon RX 5700

**Printer**
Ender 3 V2 (custom definition)

**Reproduction steps**
1. Add an STL for a plain cube or calibration cube (20x20x20)
2. Make sure that Line width = 0.40 and Walls = 3
3. Check both Alternate Extra Wall and Visible Top Skins Have Only One Wall
4. Attempt to Slice

**Screenshot(s)**
Examples with plain cube:
![image](https://user-images.githubusercontent.com/1823982/202764691-5e3076b2-6ec6-4096-8407-0f0170c32c2b.png)
![image](https://user-images.githubusercontent.com/1823982/202764823-3ad9543f-3106-4762-a7c9-a5d63e7332eb.png)

**Actual results**
Slicing Error

**Expected results**
Cube slices properly

**Project file**
[cube.zip](https://github.com/smartavionics/Cura/files/10043495/cube.zip) (3mf is inside zip because github didn't like the 3mf extension)

**Log file**
Relevant line: `2022-11-18 12:21:35,180 - ERROR - [MainThread] CuraEngineBackend.CuraEngineBackend._onBackendQuit [959]: Backend exited abnormally with return code 3221225477!`

**Comment by smartavionics** [comment]
Hi @reffu42 , thanks for the report. Fixed for the next release.

![Screenshot_2022-11-18_20-20-23](https://user-images.githubusercontent.com/585618/202795306-e06d378a-933c-418a-baf9-87663e2192ce.png)
