### ISSUE TITLE
A more recent Mesa version?

### ISSUE THREAD

**Issue by iandol** [smartavionics/Cura#203]
I am reluctant to ask as you have generously shared your Mesa build, but have you thought to upgrade Mesa to the current stable release? Again, I fully understand that you probably are happy with 21.0.1 solving your needs and don't see a need, but just thought I'd ask!

**Comment by smartavionics** [comment]
Hi @iandol , I can provide a more recent 32 and 64 bit Mesa build but I don't think it will improve the Cura display. I'll make something for the next release.

**Comment by smartavionics** [comment]
I added mesa 22.2.5 builds to https://github.com/smartavionics/Cura/releases/tag/4.20.9.

**Comment by iandol** [comment]
Thank you so much!!!!! Actually although I do use Cura with my Ultimaker 3, my main needs are for an up-to-date Mesa for other software. You originally made a post on the RPi forums, but that is now locked so I posted here. Thanks again!
