### ISSUE TITLE
Inconsistent Z-seam

### ISSUE THREAD

**Issue by meltiseugen** [smartavionics/Cura#210]
![image](https://user-images.githubusercontent.com/18147746/208922432-1af5748b-2e16-40db-ab12-8615195fbeac.png)

I know that there is a feature to not place the seam in a straight line (even though the user has a fix position specified) if the wall start in the air.

But in this case It has to start in the air no matter what because there is no other option.

Is it possible to add a checkbox to disable that "don't start in the air safeguard" and keep the seam straight no matter what?

For testing, I just used a simple sphere and sliced it with user specified seam position.

**Comment by smartavionics** [comment]
Use Z-seam alignment user specified and seam corner preference set to none and the seam should be dead straight.

**Comment by meltiseugen** [comment]
> Use Z-seam alignment user specified and seam corner preference set to none and the seam should be dead straight.

Yep, those are the settings I used for the initial image posted

![image](https://user-images.githubusercontent.com/18147746/208924837-554205c1-58c0-40c6-82fa-652df5c73ceb.png)

**Comment by smartavionics** [comment]
OK, please supply the project file so I can test it, thanks. Do File -> Save and then either rename the .3mf file to .zip or zip it up so you can attach to this issue.

**Comment by meltiseugen** [comment]
Here is the project file exported from Cura

[sphere.3mf.zip](https://github.com/smartavionics/Cura/files/10278361/sphere.3mf.zip)

**Comment by smartavionics** [comment]
Ah, yes, you're right, it moves the seam point even when the seam corner preference is none. There is a small bug here that I can fix which will make it less likely that the seam will wobble but there's also a setting change that will help you. Turn off the overhang detection by setting the overhanging wall angle to 90 and the seam will  be straight.

**Comment by meltiseugen** [comment]
> Turn off the overhang detection by setting the overhanging wall angle to 90 and the seam will be straight.

Ah, I understand now. Still, it would be nice to have this independently (or a way to decouple this) from the overhang setting. Basically, two of the most features that I'm interested in are the seam and the overhang controls haha

**Comment by smartavionics** [comment]
It's no big deal to add a setting that would disable the moving of the z-seam when it is above air.

**Comment by smartavionics** [comment]
It will be in the next release...

![Screenshot_2022-12-21_15-22-32](https://user-images.githubusercontent.com/585618/208940498-00060e6e-fefe-49da-95a5-ac3ecf6b5423.png)

**Comment by meltiseugen** [comment]
Good gracious, you are amazing! Thank you for listening to the community!

I'll close this one.
