### ISSUE TITLE
Arc Overhang

### ISSUE THREAD

**Issue by 5axes** [smartavionics/Cura#214]
After the Gradient Infill the [Arc Overhang](https://github.com/CNCKitchen/arc-overhang) . An other nice Idea from CncKitchen. Would also love to test it not in so excesive conditions.  

What do you think of this  approach to print overhang ?

**Comment by smartavionics** [comment]
To be honest, I'm not impressed. I think it is of limited usefulness and don't intend to implement it.

**Comment by kvnper** [comment]
I just want to give credit where it's due and say it's not CNCKitchen's idea but Steven McCulloch. Thanks to CNCKitchen for bringing more attention to it.

I agree that it shouldn't be implemented yet, it's still quite new and experimental. One should wait for it to mature and see if it has any mainstay.

**Comment by 5axes** [comment]
Thank you @kvnper for correcting my mistake when I read CNCKitchen's readme I thought the idea came from him. I should have seen that the repository was a fork.

**Comment by 5axes** [comment]
Should be change into discussion not Issue

**Comment by 5axes** [comment]
Should be change into discussion not issue
