### ISSUE TITLE
Bridge lines are not anchored properly when Bridge Settings is enabled

### ISSUE THREAD

**Issue by reffu42** [smartavionics/Cura#218]
**Application version**
4.20.11

**Platform**
Windows 10 Pro 

**Printer**
Ender 3 V2 (customized w/ Klipper)

**Reproduction steps**
1. Load a model with a long bridge with extended sections on either side that are filled with skin (a common temperature test such as [this](https://github.com/5axes/Calibration-Shapes/blob/master/models/TempTowerPLA190%C2%B0C.stl ) is a good example
2. With Bridge Settings disabled, slice the model
3. Notice that the bridge layer goes all the way across from wall to wall (see picture)
4. Now enable Bridge settings (seems like changing the values for the bridge settings does not affect the results)
5. Slice the model again
6. BUG: Now, small patches of skin are generated on either side, and the bridge lines are not well anchored 

**Screenshot(s)**
With Bridge Settings Disabled:
![image](https://user-images.githubusercontent.com/1823982/219128806-e62cda42-276d-46a6-92e1-5b00e9909d79.png)

With Bridge Settings Enabled:
![image](https://user-images.githubusercontent.com/1823982/219128724-7a25065d-ceb3-44c5-b1bf-00e78c469597.png)

**Actual results**
Bridge skin lines are not anchored properly to the part and do not go past the edge of the open-air section

**Expected results**
Bridge skin lines should extend a certain distance on either side of the bridge so they are properly anchored to the part.

**Project file**
[temp-tower.zip](https://github.com/smartavionics/Cura/files/10746533/temp-tower.zip)

**Comment by smartavionics** [comment]
It's not a bug, it's designed that way. If you are having problems with the bridge skin lines not adhering well you could try increasing the bridge skin overlap setting. That should extend the bridge skin further into the non-bridge skin.

**Comment by reffu42** [comment]
That makes sense, I'll play around with it and see how it turns out, thanks.

Shouldn't that be generated the same regardless of the "enable bridge settings" option?

**Comment by smartavionics** [comment]
When the bridge settings are not enabled, Cura's bridging ability is very limited. A lot of the bridging functionality is only available when those settings are enabled.
