### ISSUE TITLE
[FR] Discrete Line Definition Directory for Json file

### ISSUE THREAD

**Issue by 5axes** [smartavionics/Cura#221]
Add in the Configuration Folder a Directory to store the JSON file used to define the Discrete Line Definition : Ie

**<user>\AppData\Roaming\cura\4.20\discrete_line_definition**

Possibility to store in a dedicate folder the JSON file in order to simplify the management of the files when we use this option.  Of course Cura will search in this directory the file when we just specify a file definition like :  **@discrete1.json**   if the  discrete1.json file doesn't exist in the project directory.

Could be also interesting to List the files present in the Folder and give the possibility to select the file via a DropDown Control in the Cura Parameter section

**Comment by smartavionics** [comment]
Hi, I've finally got around to making a release and have incorporated your suggestion. The directory is called dli_definitions.

**Comment by 5axes** [comment]
Thanks a lot
