### ISSUE TITLE
Hole Horizontal Expansion Max Size and Max Length seem broken

### ISSUE THREAD

**Issue by GregValiant** [smartavionics/Cura#225]
**OpSys**
Windows 10 Home
**Printer**
Ender 3 Pro
**Cura Version**
SmartAvionics 4.20.1mb

**Reproduction steps**
1. The model has a vertical hole and an intersecting horizontal cross hole
2. Set HHE to 1.0 and HHE Max Size and Max Length to 0.
3. Sliced and noted the characteristic ridge above and below the cross hole.
4. Above and below the cross hole HHE appears to be properly applied
![image](https://github.com/smartavionics/Cura/assets/64202104/cc02c85d-2c86-4a9f-8f51-ebdbf7959bb9)

**Actual results**
1. Set the HHE Max Size to 0.1 and HHE appears to simply have turned off.
![image](https://github.com/smartavionics/Cura/assets/64202104/b57488e6-4852-42b6-ab10-8a4ece6b9b7e)

**Expected results**
HHE should be uniformly applied to the vertical hole and the "Side hole effect" should be mitigated.

**Project file**
[HHE and Max Size.zip](https://github.com/smartavionics/Cura/files/11575490/HHE.and.Max.Size.zip)

**Log file**
I don't believe this will require a log file.

**Additional information**
None

**Comment by smartavionics** [comment]
It looks to me that the feature is working as intended. When HHEML is non-zero, holes whose perimeter length is >= HHEML will NOT have HHE applied to them. Which is what your second image shows.

Edited to include vital NOT!

**Comment by GregValiant** [comment]
Then I mis-understood.
So for this particular model, that rectangular cross hole is simply an interference and the only recourse is to exempt the large vertical hole from HHE...BUT...if there were holes through the bottom they could still get the HHE?

I understand now.
The bottom hole was designed at 10mm dia. and the block resting inside is 10mm cross-corner.  So the bottom hole has HHE applied and the big vertical feature is excluded.
![image](https://github.com/smartavionics/Cura/assets/64202104/dcb81727-42d6-48c5-b109-e8b88e983b5b)

Thank you.  I'll go ahead and close this.

**Comment by smartavionics** [comment]
> The bottom hole was designed at 10mm dia. and the block resting inside is 10mm cross-corner. So the bottom hole has HHE applied and the big vertical feature is excluded.

Yup, you got it.
