### ISSUE TITLE
Zigzag for internal bridge

### ISSUE THREAD

**Issue by PhilBaz** [smartavionics/Cura#227]
**Is your feature request related to a problem? Please describe.**
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

Internal bridge is crucial for smooth top surfaces without melted lumps or other artifacts. This might improve the reliability of internal bridges?

**Describe the solution you'd like**
(A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)

Internal (and external I guess?) bridges use a line approach. But I have found if not highly tuned many of these lines will miss the edge connection and curl up, and this small issue can snowballs into a significant surface artifacts with burnt discoloration. 

I saw an image where bridging was using a zigzag pattern . This seems ideal for a few reasons, no retraction, continuous extrusion with larger edge connection contact. 

It would be great to test this option see how much difference it makes.

I think it would be nice if the zag sat on top of the inner most internal wall, rather than being placed inside of it. Or perhaps if inside the inner walls to have an option to generate skin edge support layers beneath it.

![Screenshot 2023-06-01 085728](https://github.com/smartavionics/Cura/assets/21558241/6241945f-6ad5-4d16-92e4-3876cf7d2629)

**Affected users and/or printers**
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)

anyone using bridging

**Additional context**
(Add any other context or screenshots about the feature request here.)

Hope you like... I think this could be a really useful feature.

**Comment by smartavionics** [comment]
Hi Phil. Yes, this looks like it's worth trying so I will add settings to make the bridge skin areas use zig-zag rather than lines pattern.

**Comment by PhilBaz** [comment]
@smartavionics 

Awesome!
