### ISSUE TITLE
[4.20.16 ARM64] Drag and drop not working on Wayland

### ISSUE THREAD

**Issue by Botspot** [smartavionics/Cura#241]
**Application version**
4.20.16 ARM64 AppImage

**Platform**
Raspberry Pi OS Bookworm, using Wayfire with known working Xwayland, RPi5.

**Reproduction steps**
Drag a STL file onto the print area from a file manager of your choice.

**Actual results**
Nothing happens.

**Expected results**
The model would appear on the print area.

Clicking File -> Open in Cura does successfully open an STL file, so this seems to just be an issue with drag and drop.

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)
This logging-issues link you put in the issue template is no longer leading to any useful logging information. You likely need to change the link to an earlier version relating to Cura 4.

**Additional information**
This worked fine on PiOS Bullseye which used Xorg.

**Comment by smartavionics** [comment]
Yeah, a quick google shows that drag and drop to an X11 application running under Wayland is unreliable or completely broken. If I become aware of a way of fixing this I will give it a go but, otherwise, I'm not going to spend any time on this issue.

**Comment by Botspot** [comment]
That is understandable. But I was under the impression that Cura was capable of running on Wayland natively, as per the release notes. Is that not the case? Is it possible to force Cura to use wayland by setting some environment variables?

**Comment by smartavionics** [comment]
Ah, yes, the release notes state that setting QT_QPA_PLATFORM=wayland would make it use native Wayland. That currently only works (but not perfectly) on the x86 build. I will try and make an aarch64 build that can do the same. I'll get back to you when I know more.

**Comment by smartavionics** [comment]
I rebuilt Qt with Wayland support and the resulting Cura appimage will use Wayland. Unfortunately, it has some showstopping problems. Menus don't work right in that if you click on any menu heading other than File (i.e. Edit, View, etc.) the menu pops up but then disappears to be replaced by the menu on the left and that is subsequently replaced until you end up with the File menu displayed every time. Another problem is that drag and drop now works for stl files but if you drop a 3mf file onto Cura it crashes due to some internal Qt error. These problems could possibly be fixed by using a more recent version of Qt so my next step is to try that.

**Comment by Botspot** [comment]
Thanks for the work on this. I presume a Wayland build would give a nice graphics speed boost out-of-the-box for PiOS Bookworm users, so if this can work, it would benefit everyone.

**Comment by smartavionics** [comment]
Today's update... I built a version using Qt 5.15.12 and that has fixed the problem with the menus. It still crashes when drag/dropping a .3mf file but .stl and .obj files are OK. I have therefore disabled drag/drop for .3mf files. Not a great solution but it's the best I can do for now. I have uploaded a test for you to try out. It's at https://github.com/smartavionics/Cura/releases/download/4.20.16/Cura-4.20.16-mb-aarch64-16k-wayland-test.AppImage

As for performance, Wayland doesn't provide any benefit over X11 as far as I can tell. The pi5 is noticeably faster than the pi4 so I have been experimenting with different shaders for the layer view. Hitting Ctrl-space in the layer view toggles use of a shader that's a bit more like the shader used for x86 builds. It looks a little nicer as it fills the gaps between line segments but does incur a performance hit so it's nice to be able to toggle it.

Compare these images to see the visual difference it makes...

![Screenshot_2024-01-22_20-49-52](https://github.com/smartavionics/Cura/assets/585618/3cd1c2a1-45ae-4253-8684-ce16f3e93c76)
![Screenshot_2024-01-22_20-49-39](https://github.com/smartavionics/Cura/assets/585618/9b3961dc-b086-453e-8aff-9b82b3f29d89)

**Comment by Botspot** [comment]
Thanks for the appimage to test out. I can confirm drag-and-drop works. One minor regression I noticed is that it seems to be using fewer possible colors.
Compare these two screenshots and notice that the top one (wayland) has rings of yellow color bands on the rendered model, and blocky grey rectangular chunks in the gradient at the top for the [Prepare Preview Monitor] tabs.
![20240122_15h07m54s_grim](https://github.com/smartavionics/Cura/assets/54716352/6bb76d26-0493-43b7-8121-4b53b790562a)
![20240122_15h07m10s_grim](https://github.com/smartavionics/Cura/assets/54716352/bb0da615-63f8-4faf-9ef9-d350a4efea2a)
Could this be due to the fact that My Pi5 is using the 4k kernel? I disabled the 16k kernel, in part because Cura would not launch on the 16k kernel a few months ago.

**Comment by Botspot** [comment]
Regarding shaders, I have never actually gotten the enhanced layer view working.
On Bookwork, I just ensured that `libgles-dev` and `mesa-utils` were installed, then ran your wayland test appimage again and the layers still look like this: 
![20240122_15h21m04s_grim](https://github.com/smartavionics/Cura/assets/54716352/d6a68511-4280-4764-9ba9-d4387c9dc88e)
Am I missing something here?

**Comment by smartavionics** [comment]
Are you sure you haven't enabled the force layer view compatibility option in the general preferences?

As for the prepare view images, they look the same to me?

**Comment by Botspot** [comment]
> Are you sure you haven't enabled the force layer view compatibility option in the general preferences?

That was, in fact, the case. Enabling the normal viewing mode solved that. With Ctrl+Space, I can see the performance difference between the 2 shaders. If you start going forward with releasing Wayland builds, could you change the default to use the faster shader with less polygons? On larger models with many curves I found this makes a big performance impact with a near zero visual difference.

> As for the prepare view images, they look the same to me?

Two separate areas have gradients: the flat face of the model and the UI background surrounding the [Prepare Preview Monitor] buttons. Notice how that grey band across the entire width of Cura is more blocky in my wayland screenshot when compared to your Xorg build. Something is reducing the number of used colors.
For the flat face of the model, this is harder to see on some monitors, so I have used kolourpaint to flood fill all pixels of an exact color for comparison. Thicker bands means less colors are used and the gradient is more "chunky".
Wayland:
![20240122_15h07m54s_grim-contrast-added](https://github.com/smartavionics/Cura/assets/54716352/3a53a6dc-4a7d-4bc7-98b2-7d93ec90db2f)
X:
![20240122_15h07m10s_grim-contrast-added](https://github.com/smartavionics/Cura/assets/54716352/00765003-703c-47bb-adcf-9f3039465768)

**Comment by smartavionics** [comment]
Ah, yes, I can see that effect now on my own models. Haven't a clue as to what's causing that.

BTW, the test appimage defaults to using native Wayland but you can run that same test appimage using X11 rather than Wayland by using this command line:

(unset WAYLAND_DISPLAY;./Cura-4.20.16-mb-aarch64-16k-wayland-test.AppImage)

**Comment by Botspot** [comment]
I am somewhat surprised that a build for 16k is running fine on my 4k kernel. Any thoughts? If this works everywhere, then would there be any reason to maintain 2 builds?

**Comment by smartavionics** [comment]
I need to keep the other builds because an appimage built on bookworm won't work on older systems. My build systems are still running buster.

**Comment by smartavionics** [comment]
I have fixed the loss of colour resolution, it took me almost the whole day so I hope it is appreciated.
I have updated the test build so could you please download it again and give it a go.

**Comment by Botspot** [comment]
> I have fixed the loss of colour resolution, it took me almost the whole day so I hope it is appreciated. I have updated the test build so could you please download it again and give it a go.

Test build works great. Out of curiosity, what did end up fixing the loss of color resolution? And could this be a general issue that other projects could encounter when switching to wayland?
Will this build work on Xorg fine, or will we need to adjust our installation script to install the wayland appimage on wayland distros?
Also, just wanted confirmation that you changed the default layer view shader to the faster one? It seems that you did, but I just wanted to make sure.

**Comment by smartavionics** [comment]
On 23 Jan 2024 23:19, Botspot ***@***.***> wrote:

I have fixed the loss of colour resolution, it took me almost the whole day so I hope it is appreciated. I have updated the test build so could you please download it again and give it a go.

Test build works great. Out of curiosity, what did end up fixing the loss of color resolution?

I now explicitly request 8 bits for each colour. What I don't understand is why under X11 it has always worked without doing that.

And could this be a general issue that other projects could encounter when switching to wayland?

I don't think so.

Will this build work on Xorg fine, or will we need to adjust our installation script to install the wayland appimage on wayland distros?

It will be ok for 64 bit bookworm systems using either Wayland or X11.

Also, just wanted confirmation that you changed the default layer view shader to the faster one? It seems that you did, but I just wanted to make sure.

Yes, it defaults to the faster shader

**Comment by Botspot** [comment]
@smartavionics, could you go to github and check the response to this issue you just added via email? I think some of your formatting was not intentional.
