### ISSUE TITLE
Cannot execute AppImage on Raspberry Pi 5

### ISSUE THREAD

**Issue by McNugget6750** [smartavionics/Cura#259]
Downloaded, made executable, doesn't run:

> -rwxr-xr--  1 mcnugget mcnugget 220442884 Oct  3 18:36 Cura-4.20.24-mb-armhf.AppImage
> 
>  $ ./Cura-4.20.24-mb-armhf.AppImage
> bash: ./Cura-4.20.24-mb-armhf.AppImage: cannot execute: required file not found

It doesn't give me any other output.

> $ uname -a
> Linux 6.6.51+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt1 (2024-09-26) aarch64 GNU/Linux

**Comment by smartavionics** [comment]
That's weird, it works for me on exactly the same system version. What do you get if you run it with strace ?

**Comment by McNugget6750** [comment]
> strace ./Cura-4.20.24-mb-armhf.AppImage 
execve("./Cura-4.20.24-mb-armhf.AppImage", ["./Cura-4.20.24-mb-armhf.AppImage"], 0x7fffff6bc4c0 /* 48 vars */) = -1 ENOENT (No such file or directory)
strace: exec: No such file or directory
+++ exited with 1 +++

**Comment by smartavionics** [comment]
Hi,Just noticed, you're trying to run the 32 bit appimage on a 64 bit system. You need the arch64 appimage.On 4 Oct 2024 16:03, Timo ***@***.***> wrote:

strace ./Cura-4.20.24-mb-armhf.AppImage
execve("./Cura-4.20.24-mb-armhf.AppImage", ["./Cura-4.20.24-mb-armhf.AppImage"], 0x7fffff6bc4c0 /* 48 vars */) = -1 ENOENT (No such file or directory)
strace: exec: No such file or directory
+++ exited with 1 +++

**Comment by McNugget6750** [comment]
Whoopsy! 

Thanks for pointing that one out! *facepalm*
