### ISSUE TITLE
Extra wall underneath -first- top layer and treating -first- top layer like bridge

### ISSUE THREAD

**Issue by McNugget6750** [smartavionics/Cura#262]
Bambu Studio adds one extra wall to provide improved adhesion for the first layer of the top surface.
![image](https://github.com/user-attachments/assets/d235b039-ad18-4669-adae-f865daf13fa0)
![image](https://github.com/user-attachments/assets/c1ae4ad0-1c37-4a85-8a71-df4fc9dbb1e0)

They also treat the very first layer of top as bridge allowing to set bridge and top speeds separately, resulting is fewer rips in the first layer of the top layers.
![image](https://github.com/user-attachments/assets/87a9f819-8e35-4def-9b97-fbe0c7180512)
![image](https://github.com/user-attachments/assets/839753f4-f862-4663-9841-5e0c21794914)

I also noticed they have extra settings for solid infill which is used to support TOP and is printed directly over the bridge (first layer of top).

I have tried to find settings to create the same in your Cura but was unsuccessful so far. Maybe you can point me in the right direction or consider adding this functionality in future builds?

**Comment by smartavionics** [comment]
There isn't a setting to explicitly ask for an extra wall beneath the perimeter of the first skin layer but you will get those extra walls if you are using skin edge support.

As for printing the first skin layer using bridge settings, just set the Bridge Sparse Infill Max Density setting to a value greater than the infill density and it will do just that.

**Comment by McNugget6750** [comment]
Oh sweet, I'll check both of these out and report back!

**Comment by McNugget6750** [comment]
Both do what I needed! Thanks a lot for the support!
