### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by eskeyaar** [smartavionics/Cura#31]
**Application Version**

Cura-mb-master-win64-20191124

**Platform**

Windows 64bit
**Printer**

**Steps to Reproduce**

Just downloaded and installed and overwritten on previous version win64 20190912
**Actual Results**

![image](https://user-images.githubusercontent.com/6142521/69539519-91851200-0f7c-11ea-9eb2-b82d5b3036f0.png)

**Expected results**

Should open normal as before
**Additional Information**

Previous version: Cura-mb-master-win64-20190912

**Comment by smartavionics** [comment]
From the README file that you should read...
> * 20191012 - Windows build using PyQt 5.13. **CAUTION: don't install on top of previous mb-master release, uninstall the old release first!**

**Comment by eskeyaar** [comment]
oops. Missed it. 
Thanks again.
