### ISSUE TITLE
brim/raft: printbed clearance border has infinite height

### ISSUE THREAD

**Issue by susisstrolch** [smartavionics/Cura#37]
**Application Version**
Cura Master - Cura-mb-master-x86_64-20191116.AppImage

**Platform**
Linux / AppImage

**Printer**
Velleman Vertex Delta K8800

**Steps to Reproduce**
Try to slice a barrel, using brim or raft. Lower / Upper diameter of the object is inside the clearing margin, but middle of the barrel is between inner and outer clearing margin.

**Actual Results**
Slicing is not possible, because the projection is larger than the inner clearing margin.

**Expected results**
The height of the clearing area should be either brimheight+1 or raftheight+1, so it's possible to slice such objects.

Problem will occure with any printer when the projection of the object is hitting the clearing area.

**Comment by smartavionics** [comment]
Hello, this problem is not specific to my cura builds, please post a new issue at https://github.com/Ultimaker/Cura/issues. Thanks.
