### ISSUE TITLE
[BUG]  OpenFile Icon button position

### ISSUE THREAD

**Issue by 5axes** [smartavionics/Cura#39]
I'm using the Sidebar Gui Plugin (Running with the Windows Release), and With your master release the Openfile Icon Button is displayed at a strange position ( Middle / Top of the Graphic Screen) 
![Position](https://user-images.githubusercontent.com/11015345/72741601-4405d980-3ba8-11ea-8990-cc1aace609f1.jpg)
Note : This issue is not present in the official 4.4.0 or 4.4.1 release installed on the same computer.

**Comment by smartavionics** [comment]
Hi, yes, I think there is an issue with the sidebar gui and the current UM master branch. It's not due to any changes I have made. Sorry, I can't really help with this.
