### ISSUE TITLE
V20190311 - Inner wall lines trespassing the model

### ISSUE THREAD

**Issue by amagr0** [smartavionics/Cura#4]
**Application Version** - CURA Master - V20190311
**Platform** - Win 10 Pro, 64 bit
**Display Driver** - NVIDIA GeForce 840M

I'm getting this strange inner wall lines trespassing the model:

Layer height: 300 micron
![image](https://user-images.githubusercontent.com/12901952/54120274-3a8bdc80-43ef-11e9-9dc8-06d93db51e1c.png)

Layer height: 200 micron
![image](https://user-images.githubusercontent.com/12901952/54120325-55f6e780-43ef-11e9-99c2-591794d04118.png)

Layer height: 100 micron
![image](https://user-images.githubusercontent.com/12901952/54120365-6a3ae480-43ef-11e9-8bf6-dfef439ee220.png)

[inner_lines.zip](https://github.com/smartavionics/Cura/files/2951904/inner_lines.zip)

**Comment by smartavionics** [comment]
Thanks for the report, I can confirm the bug. I will investigate... The only workaround I think is to disable the walll gap filling.

**Comment by smartavionics** [comment]
Hi @amagr0 , I think that I have fixed this problem. The dropbox release 20190311 has been updated so please try it when you can. Thanks.

**Comment by amagr0** [comment]
Yes, it seems to be solved.

Layer height: 300 micron
![image](https://user-images.githubusercontent.com/12901952/54134377-c877bf80-440f-11e9-9d88-26408cac1ffc.png)

Layer height: 200 micron
![image](https://user-images.githubusercontent.com/12901952/54134437-e2190700-440f-11e9-9398-287d788b9d73.png)

Layer height: 100 micron
![image](https://user-images.githubusercontent.com/12901952/54134478-f6f59a80-440f-11e9-8a05-81e1e7ec659f.png)
