### ISSUE TITLE
Issue with mesh modifier settings ("Mesh type: Modify settings for overlaps")

### ISSUE THREAD

**Issue by kvnper** [smartavionics/Cura#47]
First of all, thank you for your great work with your personal releases of Cura!

Using version Cura-mb-master-win64-20200226, I have run into an issue on every model I've tried so far where I cannot change the 'Per model' settings for any mesh when setting the mesh type to "Modify settings for overlap" (image below for reference) Only these two options are shown for reasons unknown (maybe from a previous saved state).

![image](https://user-images.githubusercontent.com/47488385/75619277-1449e880-5bce-11ea-9b83-4a4ed3b7edc1.png)

As you can see here in this screenshot below, I have ticked various settings but the options do not update on the left black box.

![image](https://user-images.githubusercontent.com/47488385/75619291-36dc0180-5bce-11ea-905c-06d7b80cba4f.png)

Then deselecting all models and selecting the mesh again removes any options:

![image](https://user-images.githubusercontent.com/47488385/75619300-4bb89500-5bce-11ea-8500-585f2b70967c.png)

Ticking and unticking "Infill only" brings back those two options from earlier.
![image](https://user-images.githubusercontent.com/47488385/75619310-7276cb80-5bce-11ea-951c-9637b98e32b3.png)

Rinse and repeat from the beginning.

I can confirm this works correctly in the latest official Cura 4,5

**Comment by smartavionics** [comment]
Hi, yes, it's totally broken, isn't it? Well, that's the work of the upstream UM developers, not me. I have commented on the changes they made and hopefully they will un-break it. I will see if I can make a temporary fix in the meantime.

**Comment by smartavionics** [comment]
Yes, I reverted the changes they made and it appears to work OK so I will build a release today.

**Comment by smartavionics** [comment]
0301 release now available, thanks for the bug report.
