### ISSUE TITLE
problem of quality

### ISSUE THREAD

**Issue by landrieve** [smartavionics/Cura#50]
Hi
i have a problem with the quality betwen Cura3.6 and cura master4.5 on a xyz calibration cube. I dont understand what happen (the mark upper and under the X) and why this difference. i use the same profil and the same gcode start. I use a ender3. sorry for my english;
![IMG_20200305_101026~2](https://user-images.githubusercontent.com/61863276/76061381-af064680-5f83-11ea-92cd-4fe6dff1d868.jpg)

[gcode.zip](https://github.com/smartavionics/Cura/files/4297126/gcode.zip)

**Comment by smartavionics** [comment]
Hi, the file CE3_xyzCalibration_cube cura3_6.gcode doesn't seem to contain gcode. Do you have another copy?

**Comment by smartavionics** [comment]
It looks like the contents of a file system directory in binary format!

**Comment by smartavionics** [comment]
I think the problem is likely to be the unretracted travel moves that occur on the layers at the top and bottom of the letters. Try setting the max comb distance with no retract to something small (e.g. 10).

**Comment by landrieve** [comment]
sorry for the gcode; I think this one is good.
[gcode 3_6.zip](https://github.com/smartavionics/Cura/files/4297269/gcode.3_6.zip)

**Comment by landrieve** [comment]
on cura 3.6 the max com distance is 0. i try tne print of xyz calibration cube with max comb distance =0 on cura 4.5.

**Comment by smartavionics** [comment]
No, it has to be > 0, try 10.

**Comment by landrieve** [comment]
ok, i have trying with 0 and i have the same thing that with 30. i try with 10

**Comment by landrieve** [comment]
i have trying with 10 and i have the same thing that with 30. i'm sorry but the best result for me is with the 3.6 of Cura. thank's for your help

**Comment by smartavionics** [comment]
Sorry, must be some other setting that is causing the issue.
