### ISSUE TITLE
Mesh Modifier for infill density cannot slice. Error with gradient infill

### ISSUE THREAD

**Issue by loneFunction** [smartavionics/Cura#56]
**Application Version**

cura-mb-master-20200513

**Platform**

MacOS 10.15.1

**Printer**

Monoprice MP10 (Custom)

**Steps to Reproduce**

Place mesh as modifier for overlaps. Add Infill Density as setting and set to 0. Gradient infill is disabled.
[InfillMod_PLA_06_1X_mask-v3L_MP10.zip](https://github.com/smartavionics/Cura/files/4632852/InfillMod_PLA_06_1X_mask-v3L_MP10.zip)

**Actual Results**

Errors slicing

**Expected results**

Infill in areas of overlap would be removed.

**Additional Information**

**Comment by smartavionics** [comment]
Hi, thanks for the report. Sorry about that, I can see what I have done and will fix today.

**Comment by smartavionics** [comment]
Could you please try the 20200515 build.

**Comment by loneFunction** [comment]
<img width="973" alt="Screen Shot 2020-05-15 at 11 52 28 AM" src="https://user-images.githubusercontent.com/5308216/82085982-aa0bf480-96a2-11ea-992c-720b0e80d0cc.png">
Thanks for getting on this. It is still unable to slice.

**Comment by smartavionics** [comment]
Hmm, could you try modifying that setting and see if that message goes away? Thanks.

**Comment by loneFunction** [comment]
<img width="372" alt="Screen Shot 2020-05-15 at 12 51 20 PM" src="https://user-images.githubusercontent.com/5308216/82090636-ca3fb180-96aa-11ea-8179-c01dc6f41ee2.png">
Gradient infill is set to None. Infill Density on the modifier set to 0 still errors, but setting it to 1 slices successfully.

**Comment by loneFunction** [comment]
<img width="751" alt="Screen Shot 2020-05-15 at 12 57 21 PM" src="https://user-images.githubusercontent.com/5308216/82091098-a29d1900-96ab-11ea-87b5-b7f5b2efaa2e.png">
Looks like when it does slice that it is still including some infill in areas where the overlap occurs.
I'm trying to remove all infill above the lower section to reduce travels. I wish Cura could print sections at a time instead of feature types. That way one isolated area could have infill, then walls printed and move on to the next island, instead of printing an infill line, then moving to another area and repeating. With poor quality printers/oozy nozzles that constant revisiting the same area reduces finish quality drastically. One of my biggest gripes with Cura.

**Comment by smartavionics** [comment]
Something is not right here.  There must be some cached file that hasn't got replaced by the 20200515 release. Could you please try removing the contents of ~/Library/Application\ Support/cura/master/cache

**Comment by loneFunction** [comment]
Good call. That did it. I'll make sure to include that process with every update.
Thank you again for your work on this.

**Comment by smartavionics** [comment]
Good, glad it's fixed, sorry for the hassle.
