### ISSUE TITLE
".gcode" not appended to filename when saving gcode.

### ISSUE THREAD

**Issue by earldbjr** [smartavionics/Cura#61]
**Application Version**

At least 20190823 through 20200525

**Platform**

Kubuntu 19.04-20.04

**Printer**

N/A

**Steps to Reproduce**

Slice Model
Click Save to File
Enter filename, Click Save or press Enter

**Actual Results**

Gcode is saved without filename extension, unless explicitly added by the user.

**Expected results**

.gcode is appended to the filename if not explicitly added by the user.

**Additional Information**

**Comment by smartavionics** [comment]
It works for me on Ubuntu 16.04.6. What does the file dialog show? Mine looks like this when I click on save to file...

![Screenshot_2020-05-27_19-17-15](https://user-images.githubusercontent.com/585618/83057476-d9c9dd80-a04e-11ea-8898-cb5866db7e34.png)

What is the default file type shown?

**Comment by earldbjr** [comment]
Gcode, same as yours. 
Now if you remove ".gcode" from the filename in your screenshot and click save, will it still save as a .gcode?

For a real world example, if you're copy/pasting a name to use as a filename, normally you can just paste it in and .gcode gets re-appended, but as it currently works for me I have to highlight up to the .gcode and paste.

**Comment by smartavionics** [comment]
> Now if you remove ".gcode" from the filename in your screenshot and click save, will it still save as a .gcode?

No, if you remove the suffix it doesn't append another one. I wouldn't expect it to.

Do the UM releases behave the same?

**Comment by earldbjr** [comment]
Hmm they did when I was on Windows, but now that I'm on Linux it doesn't seem to be behaving the same way, so nevermind!
