### ISSUE TITLE
Preferences/Printers/Machine settings - dialog boxes unreadable

### ISSUE THREAD

**Issue by Jens5395** [smartavionics/Cura#62]
**Application Version**
Cura-mb-master-x86_64-20200525.AppImage

**Platform**
Linux

**Printer**
any

**Steps to Reproduce**
Go to Preferences Printers Machine setting and half the text in the text boxes is missing

**Actual Results**
I can't read what is in the entry box ... ie nozzle size

**Expected results**
would be nice to see the nozzle size  (and any other numerics on that page ... text is ok for some reason

**Additional Information**
If I remember correctly, this issue is not present in the official Cura release
This issue has been present for a long time 

![Screenshot from 2020-06-04 21-34-22](https://user-images.githubusercontent.com/34412682/83845663-2dc36a80-a6be-11ea-9e62-0a26042783d9.png)

**Comment by smartavionics** [comment]
Hi, yes, it's a pain, isn't it. I see similar but not quite as bad.

![Screenshot_2020-06-05_07-56-36](https://user-images.githubusercontent.com/585618/83846172-1b6b2000-a702-11ea-8546-ac5e960f3fa9.png)

If the UM releases don't show the same problem (and I'm not sure whether that's true or not) then it will be down to the fact that I am using a more recent version of Qt than UM do.

I'll investigate although this UI stuff is not really my area.

**Comment by smartavionics** [comment]
Could you please try the 20200605 release?

**Comment by Jens5395** [comment]
Replied via email ..... problem fixed!
Thank you very much!

**Comment by smartavionics** [comment]
That's good, I'll send the fix upstream so that they can put it in UM builds if they wish.
