### ISSUE TITLE
Retraction missing 

### ISSUE THREAD

**Issue by eskeyaar** [smartavionics/Cura#67]
Hi Mark,
As you see from the picture below, there is no retraction at the top of 4 pillars, is it due to towers are thin? 
Thanks for your time.

**Application Version**

 Cura-mb-master-win64-20200703  

**Platform**
Windows64Bit

**Printer**
Any printer with any profile

**Steps to Reproduce**
<for instance, choose UM2+, normal profile, slice it. and in my project file too.
[UM2_four_square.zip](https://github.com/smartavionics/Cura/files/4903414/UM2_four_square.zip)

>

**Actual Results**
< As soon as model converges into thin, there is no retraction at all, only at one of pillar its happening that too i think its because of retracting at layer change?. Because of no retraction, lot of stringing occurs on those top sections>
![image](https://user-images.githubusercontent.com/6142521/87161673-c43a0b80-c2bc-11ea-8f82-8c0b197bee59.png)

![processed](https://user-images.githubusercontent.com/6142521/87161254-29d9c800-c2bc-11ea-9a0b-d7cdb8e06a2b.jpeg)

**Expected results**
There should be retraction all the way of model
Should be a clean model. 

**Additional Information**
Same model in Prusaslicer, does have retraction all the way to top. And seems like this is happening in older versions of cura too. Tested on Cura4.0 and 4.6, same result. or am i missing something in settings? 
Thanks
![image](https://user-images.githubusercontent.com/6142521/87161407-64dbfb80-c2bc-11ea-89d1-fd60da7e1d89.png)

**Comment by smartavionics** [comment]
Have you tried fiddling with the maximum retraction count or minimum extrusion distance window settings? They could have an influence on this behaviour.

**Comment by eskeyaar** [comment]
Yes, tried, no effect on them.

**Comment by eskeyaar** [comment]
> 
> 
> Have you tried fiddling with the maximum retraction count or minimum extrusion distance window settings? They could have an influence on this behaviour.

Update: i was wrong!, I entered value of max retraction count of 300 and now i see retraction. Earlier i checked with 120, didn't notice any difference on that value. But what is the safe value for these settings? more than 300?
Thanks for your input.

**Comment by smartavionics** [comment]
I've never changed them so I can't say what is a good limit but if you have a decent extruder that doesn't mash the filament up too badly it should be OK to use quite a high value.

**Comment by eskeyaar** [comment]
Thanks for the tip!
We can close this.
