### ISSUE TITLE
V20190319 - Incomplete Top Fill 

### ISSUE THREAD

**Issue by amagr0** [smartavionics/Cura#7]
**Application Version** - CURA Master - V20190319
**Platform** - Win 10 Pro, 64 bit
**Display Driver** - NVIDIA GeForce 840M

Hello @smartavionics,

This seems to be a bug, there is a top part on the model that is not complete in the top fill has you can see in the image below.

![image](https://user-images.githubusercontent.com/12901952/54684508-6c4a2500-4b0c-11e9-985b-27bc68d53491.png)

BTW, this is not happening with oficial Cura 4.0.0 (released yesterday)

[top_fill_bug.zip](https://github.com/smartavionics/Cura/files/2988179/top_fill_bug.zip)

**Comment by smartavionics** [comment]
Reduce the skin removal width.
