### ISSUE TITLE
[fr] recovery end of bridges, lack of material

### ISSUE THREAD

**Issue by jbalibeux** [smartavionics/Cura#71]
hello, I'm looking to perfect my bridges. especially the end of bridges.
I activate the bridge parameters. with an extrusion at 70% (approximately according to my tests) and with a little freewheel at the start to relieve the pressure, I have a very flat underside. OK
but at the end, when normal extrusion is resumed, the pressure is too low and generates a lack of material. (see photo below).

I think a parameter resembling "additional volume at the boot" but at the end of the bridge could solve this problem ... or a small pause before the resumption or other something else?

(sorry for this google translation, do not hesitate to ask me to rephrase if it is badly translated :))

[![Capture-d-cran-2020-10-20-090228.png](https://i.postimg.cc/d0BCKJYB/Capture-d-cran-2020-10-20-090228.png)](https://postimg.cc/wt1MX83y)

[![20201020-090406.jpg](https://i.postimg.cc/Y0f0Q3Cx/20201020-090406.jpg)](https://postimg.cc/T51T6nmy)

**Comment by jbalibeux** [comment]
> 
> 
> hello, I'm looking to perfect my bridges. especially the end of bridges.
> I activate the bridge parameters. with an extrusion at 70 (approximately according to my tests) and with a little freewheel at the start to relieve the pressure, I have a very flat underside. OK
> but at the end, when normal extrusion is resumed, the pressure is too low and generates a lack of material. (see photo below).
> 
> I think a parameter resembling "additional volume at the boot" but at the end of the bridge could solve this problem ... or a small pause before the resumption or other something else?
> 
> (sorry for this google translation, do not hesitate to ask me to rephrase if it is badly translated :))
> 
> ![capture cura](https://camo.githubusercontent.com/f843b0e4346e669ee33f204e08d3c755c6f4b3fe/68747470733a2f2f64726976652e676f6f676c652e636f6d2f66696c652f642f31756b327432614e4d6150483237397051692d643379662d545737795a4f5f55712f766965773f7573703d73686172696e67)
> ![photo exemple](https://camo.githubusercontent.com/b64dc0feb4e4da89f6c738195de6a1318c6df24f/68747470733a2f2f64726976652e676f6f676c652e636f6d2f66696c652f642f3137457168584e75664d655833564164576151526f7350683849524c77493637572f766965773f7573703d73686172696e67)
> I have a hard time displaying the image correctly here, I do not know github very well sorry :/
I'm trying to correct the display of images .. now

**Comment by smartavionics** [comment]
Hi, no problem with the translation. There is a setting to help it is called Bridge Wall End Boost. It increases the flow for the wall lines immediately following the bride. Hope this helps!

**Comment by jbalibeux** [comment]
this is exactly what I was looking for, thank you very much, and sorry for reporting a problem that came from me XD

I close this issue :)

**Comment by smartavionics** [comment]
OK, happy printing!
