### ISSUE TITLE
Inner wall overlap compensation causing extremely thin inner wall.

### ISSUE THREAD

**Issue by kvnper** [smartavionics/Cura#88]
**Application version**
v20201121

**Platform**
Win10 x64

**Printer**
QIDI X-Max

**Reproduction steps**
See 3mf in zip attachment and simply slice it.

**Screenshot(s)**

Screenshots are from Layer 71, wall on back side of build plate.

Inner wall overlap compensation on:
![image](https://user-images.githubusercontent.com/47488385/103189924-ee42c100-4922-11eb-9bc8-fed8fb59a7cc.png)
![image](https://user-images.githubusercontent.com/47488385/103189917-e84ce000-4922-11eb-8dea-2b45e0e7bd74.png)

Inner wall overlap compensation off:
![image](https://user-images.githubusercontent.com/47488385/103189941-01ee2780-4923-11eb-9753-590f1361c817.png)
![image](https://user-images.githubusercontent.com/47488385/103189939-fdc20a00-4922-11eb-90e0-6e4d4249a7eb.png)

**Actual results**
Inner wall not printed correctly. Seems to be too thin when **inner wall overlap compensation** is enabled.

Occurs at multiple locations in model.

**Expected results**
Inner walls printed at correct width.

**Project file**

See 3mf file in zip attached
[XMAX_red cover v4.zip](https://github.com/smartavionics/Cura/files/5745868/XMAX_red.cover.v4.zip)

**Log file**

[cura.log](https://github.com/smartavionics/Cura/files/5745873/cura.log)

**Additional information**
n/a

**Comment by kvnper** [comment]
Something else of note is that the inner wall line alternates between a green line and yellow line. The yellow side also has some odd behaviour with inner wall overlap compensation:

(Again, screenshots from layer 71, wall on back side of build plate)

Green and yellow wall separation
![image](https://user-images.githubusercontent.com/47488385/103190306-6a89d400-4924-11eb-88c0-e53112d86d08.png)


The other end of the yellow wall with odd behaviour (why is it thinning?):
![image](https://user-images.githubusercontent.com/47488385/103190321-770e2c80-4924-11eb-8463-9d7cc6e5976e.png)

**NOTE:** This issue does not go away when turning off inner wall overlap compensation (Even though the green line does get fixed):
![image](https://user-images.githubusercontent.com/47488385/103190347-96a55500-4924-11eb-83b0-dd59c3b3f37b.png)
![image](https://user-images.githubusercontent.com/47488385/103190416-f26fde00-4924-11eb-8aac-292758bbecb3.png)


Thank you!

**Comment by kvnper** [comment]
Update on yellow line: Turning on **Filter Out Tiny Gaps**  fixed this yellow line thinning behaviour. No difference seen with Compensate Inner Wall Overlap enabled or not with Filter Out Tiny Gaps enabled.


![image](https://user-images.githubusercontent.com/47488385/103190657-0536e280-4926-11eb-8110-36392cd69ba4.png)

**Comment by kvnper** [comment]
Update 2 on yellow thinning lines: I found more locations where this occurs but is **not** fixed by enabling **Filter Out Tiny Gaps**:

Screenshot from layer 14 amongst the grills:

![image](https://user-images.githubusercontent.com/47488385/103190835-bfc6e500-4926-11eb-8889-5b024e8e8ee9.png)


In some locations, it does two lines instead:
![image](https://user-images.githubusercontent.com/47488385/103190887-eab13900-4926-11eb-91ca-53551f1ed780.png)
Versus
![image](https://user-images.githubusercontent.com/47488385/103190897-f4d33780-4926-11eb-8003-cc627a8fe20a.png)

**Comment by smartavionics** [comment]
Yeah, those thinning yellow lines are not good but I'm not going to do any more work on that part of the slicer as all of my thin wall and gap filling code is going to be removed in the future when I merge in the upstream arachne code. However, I don't plan to merge that code until after UM have released a couple of versions of Cura that uses it.

**Comment by smartavionics** [comment]
A couple of suggestions, using a wall line width of 0.5 I think helps and also setting the min wall flow to something like 50% removes a lot of the thin green lines.

**Comment by kvnper** [comment]
Arachne looks quite nice. How far off, in your opinion, is it from release?

Yeah when I set the minimum wall flow it removes that wall completely and does not print anything there. I'll try the 0.5mm wall suggestion.

Thanks for your time.

Feel free to close this issue if you desire.

**Comment by smartavionics** [comment]
I am not involved with the development of Arachne so I don't have any idea of their timescales. I would think that unless they find some show-stopping problem that it will appear within the next couple of months. The first release and maybe the second that uses it will likely have some problems so I won't be looking to merge for a while. It's going to be quite a big job because my Cura has diverged from UM Cura over the years.
