### ISSUE TITLE
Where did the ARM builds go?

### ISSUE THREAD

**Issue by Botspot** [smartavionics/Cura#92]
I'm in charge of the world's most popular Raspberry Pi app store called [Pi-Apps](https://github.com/Botspot/pi-apps), and your ARM Cura builds are there for anyone to conveniently install and use. **Over 1500 people** have installed Cura through the store.

And that brings me to the present concern: In your [latest release](https://github.com/smartavionics/Cura/releases/tag/20210214), both aarch64 and armhf builds are **missing**.  
Was this a mistake? Or is this the new normal?

**Comment by smartavionics** [comment]
> And that brings me to the present concern: In your latest release, both aarch64 and armhf builds are missing.
Was this a mistake? Or is this the new normal?

They will be uploaded shortly, it takes a while to create the 6 different builds for each release and I tend to do them in random order. The Linux builds are often first because they're easiest but today I did the MacOS build first because someone was waiting for it.

**Comment by smartavionics** [comment]
They're there now...

**Comment by Botspot** [comment]
> They will be uploaded shortly, it takes a while to create the 6 different builds for each release and I tend to do them in random order. The Linux builds are often first because they're easiest but today I did the MacOS build first because someone was waiting for it.

Thank you.  
PS. have you considered adding the Pi-Apps badge to your readme?  
This would help RPi users easily install it, keep it updated, and have a start menu launcher.  
`[![badge](https://github.com/Botspot/pi-apps/blob/master/icons/badge.png?raw=true)](https://github.com/Botspot/pi-apps)  `
[![badge](https://github.com/Botspot/pi-apps/blob/master/icons/badge.png?raw=true)](https://github.com/Botspot/pi-apps)
