### ISSUE TITLE
Wrong restart value

### ISSUE THREAD

**Issue by 5axes** [smartavionics/Cura#97]
Release 20210217  Windows.

Wrong Retract value : Retraction value set to 4mm.   The value of the E axis increases gradually to finish at 140 mm at the end of the print. ( Retract mode is set to relative, just because it's more easy to analyse the result , but the issue is the same in absolute mode )

![image](https://user-images.githubusercontent.com/11015345/108631195-e4dc5d80-7468-11eb-987e-562b56caa15f.png)

[test-dog_50mm.zip](https://github.com/smartavionics/Cura/files/6018057/test-dog_50mm.zip)

**Comment by 5axes** [comment]
Just because I'm Stupid ... Postprocessor script still active !!

**Comment by smartavionics** [comment]
Ah, thanks for the update, I just sliced your project on Linux and it was using 4mm retraction as expected.

**Comment by 5axes** [comment]
Yes I'm Sorry  But it's not possible to delete an issue even if it's just because you are too stupid and  you open a report too quickly without deep analyse .

**Comment by Sophist-UK** [comment]
@5axes We have all done this at some point. Don't beat yourself up about it - just close the issue.
