### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by qwerty8224** [smartavionics/Cura#98]
please see the last layer of filling (the nozzle passes 2 times for filling) is this normal? project file attached
[DXU_1x1_fixed.zip](https://github.com/smartavionics/Cura/files/6034074/DXU_1x1_fixed.zip)

**Comment by smartavionics** [comment]
Hi, I don't understand the problem, can you provide some screen shots or a better description?

**Comment by qwerty8224** [comment]
![Снимок экрана (14)](https://user-images.githubusercontent.com/19486373/108963903-d15d0c80-768b-11eb-97dd-eaf9ddcf7d85.png)
the nozzle is already moving over the printed filling

**Comment by qwerty8224** [comment]
![Uploading Снимок экранаred.png…]()

**Comment by qwerty8224** [comment]
![Снимок экранаred](https://user-images.githubusercontent.com/19486373/108966212-f4d58680-768e-11eb-871a-1b2c29b6fb27.png)

**Comment by smartavionics** [comment]
I can see the extra infill problem now, I will investigate...

**Comment by qwerty8224** [comment]
Thank. I tried my best))) sorry for my english.
The problem is not clear sometimes happens sometimes not. It is also not clear what depends on (((
[DXU_1x1_fixed.zip](https://github.com/smartavionics/Cura/files/6034342/DXU_1x1_fixed.zip)
attached gcode

**Comment by smartavionics** [comment]
OK, I have found the bug, I am surprised it hasn't been discovered earlier. I will make a new release today that is fixed.

Thanks a lot for the report.

**Comment by qwerty8224** [comment]
thank.
I also began to rarely notice you participating in the ultimaker kura (((you have very wonderful ideas. Thanks to you, I saw how the main functions began to be implemented in the kura, thank you for your work. but I still prefer your work))))
you can get your opinion on Arachne engine alpha? and do you plan to use it later?

**Comment by smartavionics** [comment]
Hi, I have made a new release (20210224), please try it and see if the problem has gone away.

I expect I will merge the arachne work into my cura but not until at least 2 releases by UM have been made that includes it. My cura and UM cura are now quite different so the merge will be painful.

**Comment by qwerty8224** [comment]
OK. if there are any mistakes I will write. 
Checked the error went away. Things are good.

**Comment by smartavionics** [comment]
OK, thanks for the report.
